@echo off

cd /d "%~dp0"
set DIST_DIR=dist
for /f %%i in ('git config --get remote.origin.url') do set REMOTE_URL=%%i

REM build our site to %DIST_DIR% folder
call npm run build

if errorlevel 1 goto ERROR_HAPPEN

REM init git repo
if exist %DIST_DIR%/.git goto DIR_EXIST
mkdir %DIST_DIR% 2>nul
pushd %DIST_DIR%
git init
git checkout -b gh-pages
git remote add origin %REMOTE_URL%
echo # autogenerated readme > README.md
popd

REM do upload
:DIR_EXIST
pushd %DIST_DIR%
git add -A
git commit -m 'gh-pages'
git push --set-upstream origin gh-pages
popd

:ERROR_HAPPEN

pause